name: rastreo_de_entregas
description: "Apliacion de rastreo de entregas"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  url_launcher: ^6.2.4
  timeline_tile: ^2.0.0
  universal_html: ^2.2.4
  xml: ^6.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/api_config.json

  fonts:
    
    - family: Roboto
      fonts:
        -  asset: assets/Roboto-Regular.ttf
    - family: Montserrat
      fonts:
        -  asset: assets/Montserrat-Regular.ttf